// Aula: mecanismos da fórmula Prompt Mágico. Prática: caso fictício preservado.
export const CHAPTERS = [
  {id:'preparar',name:"Referência",place:"01 / REFERÊNCIA",title:"DÊ UM ALVO\nAO LOOP",
   lead:"Escolha uma referência concreta. Diga o que você quer alcançar. Transforme qualidade em critérios.",
   body:"“No nível de uma referência” tira o pedido do abstrato. Escolha um exemplo real e diga quais características importam: leitura, precisão, organização ou funcionamento. O crítico precisa desses critérios antes de ver a primeira versão.",
   action:'Definir meu critério',field:'criterion',extra:['task','reference'],
   prompt:'Complete: “Está pronto quando ___” (algo que outra pessoa confere na fonte) e “Não pode piorar: ___”. Evite palavras como claro, melhor ou profissional.',
   example:'Tarefa: revisar o comunicado interno sobre o teste do novo formulário antes de circular. Fonte: o registro do teste de 14 de maio. Pronto quando: cada frase do comunicado tem apoio numa frase do registro. Não pode piorar: a data, as medianas de 12 e 9 minutos e os grupos de 50 pedidos.',
   lesson:"“Absolutamente perfeito” expressa ambição. Quem decide se houve avanço são os critérios e a comparação, não o entusiasmo da IA.",
   source:"./prompt-magico.html",sourceName:"Prompt mágico · fórmula e mecanismos",
   question:'Você vai pedir à IA um resumo do processo para o despacho da chefia. Qual critério de pronto permite conferir o resultado?',
   choices:['Resumo claro, objetivo e em linguagem formal, em até uma página.','Cada valor, data e fundamento do resumo indica a folha do processo que o sustenta.','O resumo é aprovado por um segundo assistente de IA que o compara com o processo.'],
   correct:1,
   feedback:'Critério de pronto é algo que outra pessoa confere na fonte. Estilo e aprovação de terceiros não mostram fidelidade ao processo.',
   feedbacks:['Uma página é conferível; “claro” e “objetivo” não são. E nada nesse critério impede um valor errado, que é a falha mais cara num despacho.','Qualquer pessoa pode abrir a folha e confirmar ou negar cada fato. O critério diz o que conferir e onde.','Outra IA pode ajudar a revisar, mas isso é um jeito de conferir, não o que conta como pronto. Ela também pode errar ou deixar passar um valor.']},

  {id:'hipotese',name:"Dividir",place:"02 / DIVIDIR",title:"DIVIDA O TRABALHO.\nMANTENHA O ALVO.",
   lead:"Separe partes independentes. Dê uma entrega a cada agente. Use os mesmos critérios no conjunto.",
   body:"Divida por tema: conteúdo, visual e funcionamento, por exemplo. Cada frente recebe uma entrega, critérios, um responsável e seu próprio ciclo de produção, crítica e revisão. Trabalhe em paralelo somente nas partes independentes. Uma pessoa ou agente integrador reúne as saídas e testa a experiência completa.",
   action:'Praticar no caso',field:'hypothesis',
   prompt:'Se eu mudar ___, espero ver ___, porque ___. Desisto da ideia se ___.',
   example:'Se eu retirar do comunicado a causa e a data que o registro não sustenta, mantendo os números, espero que toda frase tenha apoio na fonte. Desisto se a nova versão perder algum dado ou ainda afirmar algo que o registro não diz.',
   lesson:"Várias frentes não significam várias pessoas editando a mesma peça. Defina quem pode alterar o quê, quais entregas dependem das outras e em que momento elas serão integradas. O limite total vale para a equipe inteira.",
   source:"./prompt-magico.html",sourceName:"Prompt mágico · fórmula e mecanismos",
   question:'Na segunda versão, você trocou o prompt, anexou o processo completo e usou outro modelo de IA. O resumo melhorou. O que você pode afirmar?',
   choices:['O novo prompt foi decisivo, porque foi a mudança mais trabalhosa.','Anexar o processo completo causou a melhora, porque a IA passou a ter a fonte.','O conjunto melhorou o resultado; para saber o que pesou, é preciso testar uma mudança por vez.'],
   correct:2,
   feedback:'Três mudanças juntas podem melhorar o resultado, mas não mostram qual delas causou a melhora.',
   feedbacks:['O esforço gasto numa mudança não indica o efeito dela. As outras duas mudanças podem explicar a melhora sozinhas.','É uma boa hipótese, mas continua sendo hipótese: o modelo também mudou. Teste só o anexo e compare.','Mudar tudo junto serve para explorar. Para atribuir a causa, compare versões que diferem em uma só coisa.']},

  {id:'executar',name:"Iterar",place:"03 / ITERAR",title:"CADA VOLTA\nPRECISA MUDAR ALGO",
   lead:"Produza uma versão visível. Receba uma crítica específica. Revise e teste novamente.",
   body:"Antes de começar, configure limites de ciclos, tempo e custo. Pare no primeiro limite atingido. O custo total inclui os produtores, os críticos, as ferramentas e as novas tentativas de todas as frentes. Mais agentes e contextos maiores podem multiplicar esse consumo; número de ciclos sozinho não limita o gasto.",
   action:'Preparar meu teste',field:'test',extra:['setup'],
   prompt:'Qual pedido vou usar, com qual fonte? Onde fica a resposta intacta? Qual é meu limite de tentativas ou de tempo?',
   example:'Pedido: “Redija um comunicado interno com base somente no registro de 14 de maio de 2026. Preserve a data, os grupos de 50 pedidos e as medianas de 12 e 9 minutos. Separe observação de causa. Não acrescente data ou autorização de adoção definitiva.” Ferramenta: assistente de IA autorizado pelo órgão, com modelo e versão anotados como aparecem no seletor e a data do uso; sem instruções fixas; busca desligada; anexo: só o registro. A resposta ficou salva, sem edição, como “comunicado_candidata”, ao lado do registro. Limite: duas tentativas.',
   lesson:"Use um painel com frente, responsável, modelo, rodada, estado, ganho observado, tempo e consumo acumulado. Mostre o saldo e permita pausar. Se a ferramenta não informa o custo real, indique estimativa ou indisponível; não invente precisão.",
   source:"./prompt-magico.html",sourceName:"Prompt mágico · fórmula e mecanismos",
   question:'A IA entregou a nova nota com a frase “todas as informações foram conferidas nos autos”. O que você guarda deste teste?',
   choices:['A nova nota ao lado da anterior, com o pedido usado; a frase da IA não conta como conferência.','A nova nota com a frase da IA, que já registra a conferência feita.','Só a nova nota, no lugar da anterior, para não circularem duas versões.'],
   correct:0,
   feedback:'Guarde a versão anterior, a nova e o pedido. Uma declaração de conferência escrita pela IA não é evidência.',
   feedbacks:['Com as duas versões e o pedido, outra pessoa consegue comparar e repetir o teste. A conferência ainda está por fazer.','A IA pode escrever que conferiu sem ter conferido. A frase é parte do texto a avaliar, não prova de nada.','Evitar confusão é legítimo, mas substituir apaga a base. Se a nova versão tiver erro, você não terá para onde voltar nem com o que comparar.']},

  {id:'avaliar',name:"Criticar",place:"04 / CRITICAR",title:"QUEM CRIA\nNÃO DÁ A NOTA",
   lead:"Separe produtor e crítico. Mostre referência e resultado. Exija falha, evidência e correção.",
   body:"Escolha um crítico rigoroso em contexto separado e, quando possível, de outro modelo. Ele recebe a referência, os critérios e o artefato, sem o elogio ou a defesa do produtor. Peça falha, evidência, impacto e reconferência. Isso busca evitar complacência; trocar o modelo não garante independência nem elimina erros compartilhados.",
   action:'Registrar minha evidência',field:'evidence',
   prompt:'Para cada frase ou critério: sustentada, não sustentada ou não verificada? Qual trecho da fonte decide? O que ficou sem conferir?',
   example:'Frase 1 (medianas de 12 e 9 minutos, 50 pedidos): sustentada pela frase 2 do registro. Frase 2 (o formulário causou a redução): não sustentada; a frase 3 diz que formulário e equipe mudaram juntos. Frase 3 (adoção em 20 de maio): não sustentada; a frase 4 trata da adoção e diz que não há data nem autorização. Frase 4 (a equipe recebeu treinamento): não verificada; nenhuma frase do registro trata de treinamento. Critério: não passou.',
   lesson:"O crítico não precisa encontrar defeitos a qualquer custo: deve aprovar o que passou e apontar exatamente o que não passou. Concordância entre modelos não substitui evidência. Para pontos importantes, confira a saída executada e use revisão humana.",
   source:"./prompt-magico.html",sourceName:"Prompt mágico · fórmula e mecanismos",
   question:'Dois colegas e uma IA revisora aprovaram a nota. Nenhum abriu as folhas citadas. Qual é o estado do critério “cada fato com a folha que o sustenta”?',
   choices:['Atende: três revisões independentes chegaram à mesma conclusão.','Não atende: sem conferência, a nota deve ser reprovada.','Não verificado: falta abrir as folhas citadas.'],
   correct:2,
   feedback:'Concordância orienta a revisão, mas não é evidência. Sem abrir a fonte, o critério continua não verificado.',
   feedbacks:['Três leituras que não abriram a fonte podem repetir o mesmo erro. Consenso sem conferência não mostra que o valor está certo.','Faltar conferência não prova que há erro. Reprovar sem evidência é tão infundado quanto aprovar sem evidência.','O estado correto é “não verificado” até alguém abrir as folhas. Registre o que falta conferir e quem vai fazer.']},

  {id:'corrigir',name:"Revisar",place:"05 / REVISAR",title:"A CRÍTICA VIRA\nA PRÓXIMA TAREFA",
   lead:"Ataque a falha apontada. Preserve o que já funciona. Reavalie a versão integrada.",
   body:"Transforme a crítica em uma tarefa pequena por frente. Corrija a falha de maior impacto, compare com a versão anterior e confira regressões. Registre o ganho de cada rodada com o mesmo critério. Se várias tentativas quase não melhoram, há um possível platô: pare para diagnosticar, em vez de pedir mais do mesmo.",
   action:'Planejar minha correção',field:'correction',
   prompt:'Qual falha foi demonstrada e em qual trecho da fonte? Qual a menor correção? O que vou conferir de novo, incluindo o que já estava certo?',
   example:'Retirei a causa atribuída ao formulário e a data de 20 de maio, e escrevi que a causa não foi isolada. Mantive a data do teste, as medianas e os grupos de 50 pedidos. Conferi de novo cada frase contra o registro: todas têm apoio.',
   lesson:"Diante do platô, reveja contexto, ferramenta, modelo ou abordagem. Mude uma hipótese por vez. Se o critério ainda não foi atendido, registre a lacuna; o platô não transforma um resultado insuficiente em sucesso.",
   source:"./prompt-magico.html",sourceName:"Prompt mágico · fórmula e mecanismos",
   question:'A versão corrigida ficou mais clara, mas perdeu o prazo de vigência do contrato, que a anterior trazia. O que fazer?',
   choices:['Recolocar o prazo a partir da versão anterior e conferir de novo a clareza e o que já atendia.','Aceitar: a clareza era o objetivo desta volta, e o prazo está nos autos.','Retirar a vigência dos critérios, já que o despacho pode ser feito sem ela.'],
   correct:0,
   feedback:'Uma perda no que já estava certo entra na decisão. Não afrouxe o critério para aceitar a nova versão.',
   feedbacks:['A correção mira a perda, aproveita a base guardada e confere de novo o ganho e o que não podia piorar.','A vigência estava em “não pode piorar”. Aceitar a perda troca uma falha visível por outra escondida no despacho.','Mudar o critério para a versão passar esconde a falha em vez de corrigi-la. Só mude um critério com motivo registrado, e não por causa desta versão.']},

  {id:'encerrar',name:"Comparar",place:"06 / COMPARAR",title:"COMPARE.\nENTÃO DECIDA.",
   lead:"Coloque as versões lado a lado. Oculte a autoria quando possível. Aceite o ganho ou abra outra volta.",
   body:"Compare as versões com os mesmos critérios e, quando possível, sem mostrar a autoria. Aceite somente o ganho verificado. Encerre quando o critério for atendido, quando um limite for atingido ou quando o ganho marginal deixar de justificar outra rodada. Registre o resultado, o consumo e a pendência de cada frente.",
   action:'Concluir meu registro',field:'next',extra:['decision'],
   prompt:'Que decisão a evidência permite, e o que ela não permite? O que ficou pendente? O que a próxima pessoa precisa saber para continuar?',
   example:'Decisão: comunicar só o resultado observado e seus limites. Não autoriza adoção definitiva nem afirma que o formulário causou a redução. Pendente: quem decide a adoção. Próxima volta: comparar os formulários com a mesma equipe, para isolar o efeito. Outra saída válida: encerrar a causa como inconclusiva até esse teste.',
   lesson:"Defina antes o que conta como ganho mínimo e quantas rodadas sem ganho justificam uma pausa. A curva do monitor é ilustrativa: loops reais podem oscilar, regredir ou melhorar de repente. A decisão usa evidência, custo restante e importância da falha.",
   source:"./prompt-magico.html",sourceName:"Prompt mágico · fórmula e mecanismos",
   question:'O prazo do despacho acaba hoje e duas afirmações continuam sem folha localizada. Como encerrar?',
   choices:['Enviar a nota como concluída, com a ressalva genérica “sujeito a conferência”.','Registrar inconclusivo para as duas afirmações, informar a lacuna à chefia e anotar o próximo passo.','Rodar o mesmo pedido na IA mais algumas vezes até as folhas aparecerem.'],
   correct:1,
   feedback:'Parar pelo limite é uma decisão válida, mas não equivale a sucesso: o que falta precisa acompanhar o registro.',
   feedbacks:['A ressalva genérica esconde quais afirmações faltam. Quem assina o despacho não sabe o que está sem prova.','A chefia decide sabendo o que foi conferido e o que não foi, e a próxima volta começa da lacuna registrada.','Repetir o mesmo pedido sem mudar nada tende a repetir o resultado e consome o prazo. Se tentar de novo, mude algo e registre a hipótese.']}
];

export const FIELDS = [
 ['task','Minha tarefa real','Ex.: revisar um comunicado ou resumir um processo. Uma tarefa pequena que você já precisa fazer.'],
 ['reference','Fonte e versão de partida','Documento, pasta ou processo de origem, e a versão atual que servirá de comparação.'],
 ['criterion','Critério de pronto e o que não pode piorar','Algo que outra pessoa confere na fonte, e o que precisa continuar certo.'],
 ['hypothesis','Hipótese','Se eu mudar…, espero ver…, porque… Desisto se…'],
 ['setup','Ferramenta, modelo e configuração','Ferramenta autorizada pelo órgão, modelo e versão como aparecem na tela, data, instruções fixas, busca ligada ou desligada e anexos.'],
 ['test','Teste e limite','Pedido usado, onde salvei a resposta intacta e o limite de tentativas ou tempo.'],
 ['evidence','Evidência por frase ou critério','Sustentada, não sustentada ou não verificada, e o trecho da fonte que decide.'],
 ['correction','Correção e reconferência','Falha corrigida, o que mudou e o que conferi de novo.'],
 ['next','Pendência e próxima volta','O que ficou em aberto e o que a próxima pessoa precisa saber.']
];
